apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../../base
- secret.yaml

configMapGenerator:
  - name: dex
    files:
      - dex-config.yaml

patches:
- path: configmap.yaml
